"""update analysis table

Revision ID: a76cdc018a71
Revises: 85bf05a18bfe
Create Date: 2026-07-15 10:37:05.782880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a76cdc018a71'
down_revision: Union[str, Sequence[str], None] = '85bf05a18bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analysis', 'resume_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('analysis', 'job_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('analysis', 'match_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analysis', 'strengths',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('analysis', 'missing_skills',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('analysis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('analysis', 'missing_skills',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('analysis', 'strengths',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('analysis', 'match_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analysis', 'job_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('analysis', 'resume_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('analysis', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
